 
from open_webui.views.retrieval import (
    get_embedding_function,
)

from .config import (
    # Ollama
    ENABLE_OLLAMA_API,
    OLLAMA_BASE_URLS,
    OLLAMA_API_CONFIGS,
    # OpenAI
    ENABLE_OPENAI_API,
    OPENAI_API_BASE_URLS,
    OPENAI_API_KEYS,
    OPENAI_API_CONFIGS,
    # Direct Connections
    ENABLE_DIRECT_CONNECTIONS,
    # Tool Server Configs
    TOOL_SERVER_CONNECTIONS,
    # Code Execution
    ENABLE_CODE_EXECUTION,
    CODE_EXECUTION_ENGINE,
    CODE_EXECUTION_JUPYTER_URL,
    CODE_EXECUTION_JUPYTER_AUTH,
    CODE_EXECUTION_JUPYTER_AUTH_TOKEN,
    CODE_EXECUTION_JUPYTER_AUTH_PASSWORD,
    CODE_EXECUTION_JUPYTER_TIMEOUT,
    ENABLE_CODE_INTERPRETER,
    CODE_INTERPRETER_ENGINE,
    CODE_INTERPRETER_PROMPT_TEMPLATE,
    CODE_INTERPRETER_JUPYTER_URL,
    CODE_INTERPRETER_JUPYTER_AUTH,
    CODE_INTERPRETER_JUPYTER_AUTH_TOKEN,
    CODE_INTERPRETER_JUPYTER_AUTH_PASSWORD,
    CODE_INTERPRETER_JUPYTER_TIMEOUT,
    # Image
    AUTOMATIC1111_API_AUTH,
    AUTOMATIC1111_BASE_URL,
    AUTOMATIC1111_CFG_SCALE,
    AUTOMATIC1111_SAMPLER,
    AUTOMATIC1111_SCHEDULER,
    COMFYUI_BASE_URL,
    COMFYUI_API_KEY,
    COMFYUI_WORKFLOW,
    COMFYUI_WORKFLOW_NODES,
    ENABLE_IMAGE_GENERATION,
    ENABLE_IMAGE_PROMPT_GENERATION,
    IMAGE_GENERATION_ENGINE,
    IMAGE_GENERATION_MODEL,
    IMAGE_SIZE,
    IMAGE_STEPS,
    IMAGES_OPENAI_API_BASE_URL,
    IMAGES_OPENAI_API_KEY,
    IMAGES_GEMINI_API_BASE_URL,
    IMAGES_GEMINI_API_KEY,
    # Audio
    AUDIO_STT_ENGINE,
    AUDIO_STT_MODEL,
    AUDIO_STT_OPENAI_API_BASE_URL,
    AUDIO_STT_OPENAI_API_KEY,
    AUDIO_STT_AZURE_API_KEY,
    AUDIO_STT_AZURE_REGION,
    AUDIO_STT_AZURE_LOCALES,
    AUDIO_TTS_API_KEY,
    AUDIO_TTS_ENGINE,
    AUDIO_TTS_MODEL,
    AUDIO_TTS_OPENAI_API_BASE_URL,
    AUDIO_TTS_OPENAI_API_KEY,
    AUDIO_TTS_SPLIT_ON,
    AUDIO_TTS_VOICE,
    AUDIO_TTS_AZURE_SPEECH_REGION,
    AUDIO_TTS_AZURE_SPEECH_OUTPUT_FORMAT,
    PLAYWRIGHT_WS_URL,
    PLAYWRIGHT_TIMEOUT,
    FIRECRAWL_API_BASE_URL,
    FIRECRAWL_API_KEY,
    WEB_LOADER_ENGINE,
    WHISPER_MODEL,
    WHISPER_VAD_FILTER,
    DEEPGRAM_API_KEY,
    # Retrieval
    RAG_TEMPLATE,
    RAG_FULL_CONTEXT,
    BYPASS_EMBEDDING_AND_RETRIEVAL,
    RAG_EMBEDDING_MODEL,
    RAG_EMBEDDING_MODEL_AUTO_UPDATE,
    RAG_RERANKING_MODEL,
    RAG_RERANKING_MODEL_AUTO_UPDATE,
    RAG_EMBEDDING_ENGINE,
    RAG_EMBEDDING_BATCH_SIZE,
    RAG_RELEVANCE_THRESHOLD,
    RAG_FILE_MAX_COUNT,
    RAG_FILE_MAX_SIZE,
    RAG_OPENAI_API_BASE_URL,
    RAG_OPENAI_API_KEY,
    RAG_OLLAMA_BASE_URL,
    RAG_OLLAMA_API_KEY,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    CONTENT_EXTRACTION_ENGINE,
    TIKA_SERVER_URL,
    DOCLING_SERVER_URL,
    DOCUMENT_INTELLIGENCE_ENDPOINT,
    DOCUMENT_INTELLIGENCE_KEY,
    MISTRAL_OCR_API_KEY,
    RAG_TOP_K,
    RAG_TOP_K_RERANKER,
    RAG_TEXT_SPLITTER,
    TIKTOKEN_ENCODING_NAME,
    PDF_EXTRACT_IMAGES,
    YOUTUBE_LOADER_LANGUAGE,
    YOUTUBE_LOADER_PROXY_URL,
    # Retrieval (Web Search)
    ENABLE_WEB_SEARCH,
    WEB_SEARCH_ENGINE,
    BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL,
    WEB_SEARCH_RESULT_COUNT,
    WEB_SEARCH_CONCURRENT_REQUESTS,
    WEB_SEARCH_TRUST_ENV,
    WEB_SEARCH_DOMAIN_FILTER_LIST,
    JINA_API_KEY,
    SEARCHAPI_API_KEY,
    SEARCHAPI_ENGINE,
    SERPAPI_API_KEY,
    SERPAPI_ENGINE,
    SEARXNG_QUERY_URL,
    SERPER_API_KEY,
    SERPLY_API_KEY,
    SERPSTACK_API_KEY,
    SERPSTACK_HTTPS,
    TAVILY_API_KEY,
    TAVILY_EXTRACT_DEPTH,
    BING_SEARCH_V7_ENDPOINT,
    BING_SEARCH_V7_SUBSCRIPTION_KEY,
    BRAVE_SEARCH_API_KEY,
    EXA_API_KEY,
    PERPLEXITY_API_KEY,
    SOUGOU_API_SID,
    SOUGOU_API_SK,
    KAGI_SEARCH_API_KEY,
    MOJEEK_SEARCH_API_KEY,
    BOCHA_SEARCH_API_KEY,
    GOOGLE_PSE_API_KEY,
    GOOGLE_PSE_ENGINE_ID,
    GOOGLE_DRIVE_CLIENT_ID,
    GOOGLE_DRIVE_API_KEY,
    ONEDRIVE_CLIENT_ID,
    ENABLE_RAG_HYBRID_SEARCH,
    ENABLE_WEB_LOADER_SSL_VERIFICATION,
    ENABLE_GOOGLE_DRIVE_INTEGRATION,
    ENABLE_ONEDRIVE_INTEGRATION,
    # WebUI
    WEBUI_AUTH,
    WEBUI_NAME,
    WEBUI_BANNERS,
    WEBHOOK_URL,
    ADMIN_EMAIL,
    SHOW_ADMIN_DETAILS,
    ENABLE_SIGNUP,
    ENABLE_LOGIN_FORM,
    ENABLE_API_KEY,
    ENABLE_API_KEY_ENDPOINT_RESTRICTIONS,
    API_KEY_ALLOWED_ENDPOINTS,
    ENABLE_CHANNELS,
    ENABLE_COMMUNITY_SHARING,
    ENABLE_MESSAGE_RATING,
    ENABLE_USER_WEBHOOKS,
    ENABLE_EVALUATION_ARENA_MODELS,
    USER_PERMISSIONS,
    DEFAULT_USER_ROLE,
    DEFAULT_PROMPT_SUGGESTIONS,
    DEFAULT_MODELS,
    MODEL_ORDER_LIST,
    EVALUATION_ARENA_MODELS,
    # WebUI (LDAP)
    ENABLE_LDAP,
    LDAP_SERVER_LABEL,
    LDAP_SERVER_HOST,
    LDAP_SERVER_PORT,
    LDAP_ATTRIBUTE_FOR_MAIL,
    LDAP_ATTRIBUTE_FOR_USERNAME,
    LDAP_SEARCH_FILTERS,
    LDAP_SEARCH_BASE,
    LDAP_APP_DN,
    LDAP_APP_PASSWORD,
    LDAP_USE_TLS,
    LDAP_CA_CERT_FILE,
    LDAP_CIPHERS,
    # Misc
    ENV,
    CACHE_DIR,
    STATIC_DIR,
    FRONTEND_BUILD_DIR,
    CORS_ALLOW_ORIGIN,
    DEFAULT_LOCALE,
    WEBUI_URL,
    # Tasks
    TASK_MODEL,
    TASK_MODEL_EXTERNAL,
    ENABLE_TAGS_GENERATION,
    ENABLE_TITLE_GENERATION,
    ENABLE_SEARCH_QUERY_GENERATION,
    ENABLE_RETRIEVAL_QUERY_GENERATION,
    ENABLE_AUTOCOMPLETE_GENERATION,
    TITLE_GENERATION_PROMPT_TEMPLATE,
    TAGS_GENERATION_PROMPT_TEMPLATE,
    IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE,
    TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE,
    QUERY_GENERATION_PROMPT_TEMPLATE,
    AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE,
    AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH,
    AppConfig,
)
from open_webui.env import (
    AUDIT_EXCLUDED_PATHS,
    AUDIT_LOG_LEVEL,
    GLOBAL_LOG_LEVEL,
    MAX_BODY_LOG_SIZE,
    SAFE_MODE,
    SRC_LOG_LEVELS,
    VERSION,
    WEBUI_BUILD_HASH,
    WEBUI_AUTH_TRUSTED_EMAIL_HEADER,
    WEBUI_AUTH_TRUSTED_NAME_HEADER,
    ENABLE_WEBSOCKET_SUPPORT,
    BYPASS_MODEL_ACCESS_CONTROL,
    EXTERNAL_PWA_MANIFEST_URL,
)

def init_app_config(app):
    app.state.config = AppConfig()
    
    app.state.WEBUI_NAME = 'JumpServer Chat'
    
    ########################################
    #
    # OLLAMA
    #
    ########################################
    
    
    app.state.config.ENABLE_OLLAMA_API = ENABLE_OLLAMA_API
    app.state.config.OLLAMA_BASE_URLS = OLLAMA_BASE_URLS
    app.state.config.OLLAMA_API_CONFIGS = OLLAMA_API_CONFIGS
    
    app.state.OLLAMA_MODELS = {}
    
    ########################################
    #
    # OPENAI
    #
    ########################################
    
    app.state.config.ENABLE_OPENAI_API = ENABLE_OPENAI_API
    app.state.config.OPENAI_API_BASE_URLS = OPENAI_API_BASE_URLS
    app.state.config.OPENAI_API_KEYS = OPENAI_API_KEYS
    app.state.config.OPENAI_API_CONFIGS = OPENAI_API_CONFIGS
    
    app.state.OPENAI_MODELS = {}
    
    ########################################
    #
    # TOOL SERVERS
    #
    ########################################
    
    app.state.config.TOOL_SERVER_CONNECTIONS = TOOL_SERVER_CONNECTIONS
    app.state.TOOL_SERVERS = []
    
    ########################################
    #
    # DIRECT CONNECTIONS
    #
    ########################################
    
    app.state.config.ENABLE_DIRECT_CONNECTIONS = ENABLE_DIRECT_CONNECTIONS
    
    ########################################
    #
    # WEBUI
    #
    ########################################
    
    app.state.config.WEBUI_URL = WEBUI_URL
    app.state.config.ENABLE_SIGNUP = ENABLE_SIGNUP
    app.state.config.ENABLE_LOGIN_FORM = ENABLE_LOGIN_FORM
    
    app.state.config.ENABLE_API_KEY = ENABLE_API_KEY
    app.state.config.ENABLE_API_KEY_ENDPOINT_RESTRICTIONS = (
        ENABLE_API_KEY_ENDPOINT_RESTRICTIONS
    )
    app.state.config.API_KEY_ALLOWED_ENDPOINTS = API_KEY_ALLOWED_ENDPOINTS
    
    app.state.config.SHOW_ADMIN_DETAILS = SHOW_ADMIN_DETAILS
    app.state.config.ADMIN_EMAIL = ADMIN_EMAIL
    
    app.state.config.DEFAULT_MODELS = DEFAULT_MODELS
    app.state.config.DEFAULT_PROMPT_SUGGESTIONS = DEFAULT_PROMPT_SUGGESTIONS
    app.state.config.DEFAULT_USER_ROLE = DEFAULT_USER_ROLE
    
    app.state.config.USER_PERMISSIONS = USER_PERMISSIONS
    app.state.config.WEBHOOK_URL = WEBHOOK_URL
    app.state.config.BANNERS = WEBUI_BANNERS
    app.state.config.MODEL_ORDER_LIST = MODEL_ORDER_LIST
    
    app.state.config.ENABLE_CHANNELS = ENABLE_CHANNELS
    app.state.config.ENABLE_COMMUNITY_SHARING = ENABLE_COMMUNITY_SHARING
    app.state.config.ENABLE_MESSAGE_RATING = ENABLE_MESSAGE_RATING
    app.state.config.ENABLE_USER_WEBHOOKS = ENABLE_USER_WEBHOOKS
    
    app.state.config.ENABLE_EVALUATION_ARENA_MODELS = ENABLE_EVALUATION_ARENA_MODELS
    app.state.config.EVALUATION_ARENA_MODELS = EVALUATION_ARENA_MODELS
    
    app.state.config.ENABLE_LDAP = ENABLE_LDAP
    app.state.config.LDAP_SERVER_LABEL = LDAP_SERVER_LABEL
    app.state.config.LDAP_SERVER_HOST = LDAP_SERVER_HOST
    app.state.config.LDAP_SERVER_PORT = LDAP_SERVER_PORT
    app.state.config.LDAP_ATTRIBUTE_FOR_MAIL = LDAP_ATTRIBUTE_FOR_MAIL
    app.state.config.LDAP_ATTRIBUTE_FOR_USERNAME = LDAP_ATTRIBUTE_FOR_USERNAME
    app.state.config.LDAP_APP_DN = LDAP_APP_DN
    app.state.config.LDAP_APP_PASSWORD = LDAP_APP_PASSWORD
    app.state.config.LDAP_SEARCH_BASE = LDAP_SEARCH_BASE
    app.state.config.LDAP_SEARCH_FILTERS = LDAP_SEARCH_FILTERS
    app.state.config.LDAP_USE_TLS = LDAP_USE_TLS
    app.state.config.LDAP_CA_CERT_FILE = LDAP_CA_CERT_FILE
    app.state.config.LDAP_CIPHERS = LDAP_CIPHERS
    
    app.state.AUTH_TRUSTED_EMAIL_HEADER = WEBUI_AUTH_TRUSTED_EMAIL_HEADER
    app.state.AUTH_TRUSTED_NAME_HEADER = WEBUI_AUTH_TRUSTED_NAME_HEADER
    app.state.EXTERNAL_PWA_MANIFEST_URL = EXTERNAL_PWA_MANIFEST_URL
    
    app.state.USER_COUNT = None
    app.state.TOOLS = {}
    app.state.FUNCTIONS = {}
    
    ########################################
    #
    # RETRIEVAL
    #
    ########################################
    
    
    app.state.config.TOP_K = RAG_TOP_K
    app.state.config.TOP_K_RERANKER = RAG_TOP_K_RERANKER
    app.state.config.RELEVANCE_THRESHOLD = RAG_RELEVANCE_THRESHOLD
    app.state.config.FILE_MAX_SIZE = RAG_FILE_MAX_SIZE
    app.state.config.FILE_MAX_COUNT = RAG_FILE_MAX_COUNT
    
    app.state.config.RAG_FULL_CONTEXT = RAG_FULL_CONTEXT
    app.state.config.BYPASS_EMBEDDING_AND_RETRIEVAL = BYPASS_EMBEDDING_AND_RETRIEVAL
    app.state.config.ENABLE_RAG_HYBRID_SEARCH = ENABLE_RAG_HYBRID_SEARCH
    app.state.config.ENABLE_WEB_LOADER_SSL_VERIFICATION = ENABLE_WEB_LOADER_SSL_VERIFICATION
    
    app.state.config.CONTENT_EXTRACTION_ENGINE = CONTENT_EXTRACTION_ENGINE
    app.state.config.TIKA_SERVER_URL = TIKA_SERVER_URL
    app.state.config.DOCLING_SERVER_URL = DOCLING_SERVER_URL
    app.state.config.DOCUMENT_INTELLIGENCE_ENDPOINT = DOCUMENT_INTELLIGENCE_ENDPOINT
    app.state.config.DOCUMENT_INTELLIGENCE_KEY = DOCUMENT_INTELLIGENCE_KEY
    app.state.config.MISTRAL_OCR_API_KEY = MISTRAL_OCR_API_KEY
    
    app.state.config.TEXT_SPLITTER = RAG_TEXT_SPLITTER
    app.state.config.TIKTOKEN_ENCODING_NAME = TIKTOKEN_ENCODING_NAME
    
    app.state.config.CHUNK_SIZE = CHUNK_SIZE
    app.state.config.CHUNK_OVERLAP = CHUNK_OVERLAP
    
    app.state.config.RAG_EMBEDDING_ENGINE = RAG_EMBEDDING_ENGINE
    app.state.config.RAG_EMBEDDING_MODEL = RAG_EMBEDDING_MODEL
    app.state.config.RAG_EMBEDDING_BATCH_SIZE = RAG_EMBEDDING_BATCH_SIZE
    app.state.config.RAG_RERANKING_MODEL = RAG_RERANKING_MODEL
    app.state.config.RAG_TEMPLATE = RAG_TEMPLATE
    
    app.state.config.RAG_OPENAI_API_BASE_URL = RAG_OPENAI_API_BASE_URL
    app.state.config.RAG_OPENAI_API_KEY = RAG_OPENAI_API_KEY
    
    app.state.config.RAG_OLLAMA_BASE_URL = RAG_OLLAMA_BASE_URL
    app.state.config.RAG_OLLAMA_API_KEY = RAG_OLLAMA_API_KEY
    
    app.state.config.PDF_EXTRACT_IMAGES = PDF_EXTRACT_IMAGES
    
    app.state.config.YOUTUBE_LOADER_LANGUAGE = YOUTUBE_LOADER_LANGUAGE
    app.state.config.YOUTUBE_LOADER_PROXY_URL = YOUTUBE_LOADER_PROXY_URL
    
    app.state.config.ENABLE_WEB_SEARCH = ENABLE_WEB_SEARCH
    app.state.config.WEB_SEARCH_ENGINE = WEB_SEARCH_ENGINE
    app.state.config.WEB_SEARCH_DOMAIN_FILTER_LIST = WEB_SEARCH_DOMAIN_FILTER_LIST
    app.state.config.WEB_SEARCH_RESULT_COUNT = WEB_SEARCH_RESULT_COUNT
    app.state.config.WEB_SEARCH_CONCURRENT_REQUESTS = WEB_SEARCH_CONCURRENT_REQUESTS
    app.state.config.WEB_LOADER_ENGINE = WEB_LOADER_ENGINE
    app.state.config.WEB_SEARCH_TRUST_ENV = WEB_SEARCH_TRUST_ENV
    app.state.config.BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL = (
        BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL
    )
    
    app.state.config.ENABLE_GOOGLE_DRIVE_INTEGRATION = ENABLE_GOOGLE_DRIVE_INTEGRATION
    app.state.config.ENABLE_ONEDRIVE_INTEGRATION = ENABLE_ONEDRIVE_INTEGRATION
    app.state.config.SEARXNG_QUERY_URL = SEARXNG_QUERY_URL
    app.state.config.GOOGLE_PSE_API_KEY = GOOGLE_PSE_API_KEY
    app.state.config.GOOGLE_PSE_ENGINE_ID = GOOGLE_PSE_ENGINE_ID
    app.state.config.BRAVE_SEARCH_API_KEY = BRAVE_SEARCH_API_KEY
    app.state.config.KAGI_SEARCH_API_KEY = KAGI_SEARCH_API_KEY
    app.state.config.MOJEEK_SEARCH_API_KEY = MOJEEK_SEARCH_API_KEY
    app.state.config.BOCHA_SEARCH_API_KEY = BOCHA_SEARCH_API_KEY
    app.state.config.SERPSTACK_API_KEY = SERPSTACK_API_KEY
    app.state.config.SERPSTACK_HTTPS = SERPSTACK_HTTPS
    app.state.config.SERPER_API_KEY = SERPER_API_KEY
    app.state.config.SERPLY_API_KEY = SERPLY_API_KEY
    app.state.config.TAVILY_API_KEY = TAVILY_API_KEY
    app.state.config.SEARCHAPI_API_KEY = SEARCHAPI_API_KEY
    app.state.config.SEARCHAPI_ENGINE = SEARCHAPI_ENGINE
    app.state.config.SERPAPI_API_KEY = SERPAPI_API_KEY
    app.state.config.SERPAPI_ENGINE = SERPAPI_ENGINE
    app.state.config.JINA_API_KEY = JINA_API_KEY
    app.state.config.BING_SEARCH_V7_ENDPOINT = BING_SEARCH_V7_ENDPOINT
    app.state.config.BING_SEARCH_V7_SUBSCRIPTION_KEY = BING_SEARCH_V7_SUBSCRIPTION_KEY
    app.state.config.EXA_API_KEY = EXA_API_KEY
    app.state.config.PERPLEXITY_API_KEY = PERPLEXITY_API_KEY
    app.state.config.SOUGOU_API_SID = SOUGOU_API_SID
    app.state.config.SOUGOU_API_SK = SOUGOU_API_SK
    
    app.state.config.PLAYWRIGHT_WS_URL = PLAYWRIGHT_WS_URL
    app.state.config.PLAYWRIGHT_TIMEOUT = PLAYWRIGHT_TIMEOUT
    app.state.config.FIRECRAWL_API_BASE_URL = FIRECRAWL_API_BASE_URL
    app.state.config.FIRECRAWL_API_KEY = FIRECRAWL_API_KEY
    app.state.config.TAVILY_EXTRACT_DEPTH = TAVILY_EXTRACT_DEPTH
    
    app.state.EMBEDDING_FUNCTION = None
    app.state.ef = None
    app.state.rf = None
    
    app.state.YOUTUBE_LOADER_TRANSLATION = None
    
    # try:
    #     app.state.ef = get_ef(
    #         app.state.config.RAG_EMBEDDING_ENGINE,
    #         app.state.config.RAG_EMBEDDING_MODEL,
    #         RAG_EMBEDDING_MODEL_AUTO_UPDATE,
    #     )
    #
    #     app.state.rf = get_rf(
    #         app.state.config.RAG_RERANKING_MODEL,
    #         RAG_RERANKING_MODEL_AUTO_UPDATE,
    #     )
    # except Exception as e:
    #     log.error(f"Error updating models: {e}")
    #     pass
    
    app.state.EMBEDDING_FUNCTION = get_embedding_function(
        app.state.config.RAG_EMBEDDING_ENGINE,
        app.state.config.RAG_EMBEDDING_MODEL,
        app.state.ef,
        (
            app.state.config.RAG_OPENAI_API_BASE_URL
            if app.state.config.RAG_EMBEDDING_ENGINE == "openai"
            else app.state.config.RAG_OLLAMA_BASE_URL
        ),
        (
            app.state.config.RAG_OPENAI_API_KEY
            if app.state.config.RAG_EMBEDDING_ENGINE == "openai"
            else app.state.config.RAG_OLLAMA_API_KEY
        ),
        app.state.config.RAG_EMBEDDING_BATCH_SIZE,
    )
    
    ########################################
    #
    # CODE EXECUTION
    #
    ########################################
    
    app.state.config.ENABLE_CODE_EXECUTION = ENABLE_CODE_EXECUTION
    app.state.config.CODE_EXECUTION_ENGINE = CODE_EXECUTION_ENGINE
    app.state.config.CODE_EXECUTION_JUPYTER_URL = CODE_EXECUTION_JUPYTER_URL
    app.state.config.CODE_EXECUTION_JUPYTER_AUTH = CODE_EXECUTION_JUPYTER_AUTH
    app.state.config.CODE_EXECUTION_JUPYTER_AUTH_TOKEN = CODE_EXECUTION_JUPYTER_AUTH_TOKEN
    app.state.config.CODE_EXECUTION_JUPYTER_AUTH_PASSWORD = (
        CODE_EXECUTION_JUPYTER_AUTH_PASSWORD
    )
    app.state.config.CODE_EXECUTION_JUPYTER_TIMEOUT = CODE_EXECUTION_JUPYTER_TIMEOUT
    
    app.state.config.ENABLE_CODE_INTERPRETER = ENABLE_CODE_INTERPRETER
    app.state.config.CODE_INTERPRETER_ENGINE = CODE_INTERPRETER_ENGINE
    app.state.config.CODE_INTERPRETER_PROMPT_TEMPLATE = CODE_INTERPRETER_PROMPT_TEMPLATE
    
    app.state.config.CODE_INTERPRETER_JUPYTER_URL = CODE_INTERPRETER_JUPYTER_URL
    app.state.config.CODE_INTERPRETER_JUPYTER_AUTH = CODE_INTERPRETER_JUPYTER_AUTH
    app.state.config.CODE_INTERPRETER_JUPYTER_AUTH_TOKEN = (
        CODE_INTERPRETER_JUPYTER_AUTH_TOKEN
    )
    app.state.config.CODE_INTERPRETER_JUPYTER_AUTH_PASSWORD = (
        CODE_INTERPRETER_JUPYTER_AUTH_PASSWORD
    )
    app.state.config.CODE_INTERPRETER_JUPYTER_TIMEOUT = CODE_INTERPRETER_JUPYTER_TIMEOUT
    
    ########################################
    #
    # IMAGES
    #
    ########################################
    
    app.state.config.IMAGE_GENERATION_ENGINE = IMAGE_GENERATION_ENGINE
    app.state.config.ENABLE_IMAGE_GENERATION = ENABLE_IMAGE_GENERATION
    app.state.config.ENABLE_IMAGE_PROMPT_GENERATION = ENABLE_IMAGE_PROMPT_GENERATION
    
    app.state.config.IMAGES_OPENAI_API_BASE_URL = IMAGES_OPENAI_API_BASE_URL
    app.state.config.IMAGES_OPENAI_API_KEY = IMAGES_OPENAI_API_KEY
    
    app.state.config.IMAGES_GEMINI_API_BASE_URL = IMAGES_GEMINI_API_BASE_URL
    app.state.config.IMAGES_GEMINI_API_KEY = IMAGES_GEMINI_API_KEY
    
    app.state.config.IMAGE_GENERATION_MODEL = IMAGE_GENERATION_MODEL
    
    app.state.config.AUTOMATIC1111_BASE_URL = AUTOMATIC1111_BASE_URL
    app.state.config.AUTOMATIC1111_API_AUTH = AUTOMATIC1111_API_AUTH
    app.state.config.AUTOMATIC1111_CFG_SCALE = AUTOMATIC1111_CFG_SCALE
    app.state.config.AUTOMATIC1111_SAMPLER = AUTOMATIC1111_SAMPLER
    app.state.config.AUTOMATIC1111_SCHEDULER = AUTOMATIC1111_SCHEDULER
    app.state.config.COMFYUI_BASE_URL = COMFYUI_BASE_URL
    app.state.config.COMFYUI_API_KEY = COMFYUI_API_KEY
    app.state.config.COMFYUI_WORKFLOW = COMFYUI_WORKFLOW
    app.state.config.COMFYUI_WORKFLOW_NODES = COMFYUI_WORKFLOW_NODES
    
    app.state.config.IMAGE_SIZE = IMAGE_SIZE
    app.state.config.IMAGE_STEPS = IMAGE_STEPS
    
    ########################################
    #
    # AUDIO
    #
    ########################################
    
    app.state.config.STT_OPENAI_API_BASE_URL = AUDIO_STT_OPENAI_API_BASE_URL
    app.state.config.STT_OPENAI_API_KEY = AUDIO_STT_OPENAI_API_KEY
    app.state.config.STT_ENGINE = AUDIO_STT_ENGINE
    app.state.config.STT_MODEL = AUDIO_STT_MODEL
    
    app.state.config.WHISPER_MODEL = WHISPER_MODEL
    app.state.config.WHISPER_VAD_FILTER = WHISPER_VAD_FILTER
    app.state.config.DEEPGRAM_API_KEY = DEEPGRAM_API_KEY
    
    app.state.config.AUDIO_STT_AZURE_API_KEY = AUDIO_STT_AZURE_API_KEY
    app.state.config.AUDIO_STT_AZURE_REGION = AUDIO_STT_AZURE_REGION
    app.state.config.AUDIO_STT_AZURE_LOCALES = AUDIO_STT_AZURE_LOCALES
    
    app.state.config.TTS_OPENAI_API_BASE_URL = AUDIO_TTS_OPENAI_API_BASE_URL
    app.state.config.TTS_OPENAI_API_KEY = AUDIO_TTS_OPENAI_API_KEY
    app.state.config.TTS_ENGINE = AUDIO_TTS_ENGINE
    app.state.config.TTS_MODEL = AUDIO_TTS_MODEL
    app.state.config.TTS_VOICE = AUDIO_TTS_VOICE
    app.state.config.TTS_API_KEY = AUDIO_TTS_API_KEY
    app.state.config.TTS_SPLIT_ON = AUDIO_TTS_SPLIT_ON
    
    app.state.config.TTS_AZURE_SPEECH_REGION = AUDIO_TTS_AZURE_SPEECH_REGION
    app.state.config.TTS_AZURE_SPEECH_OUTPUT_FORMAT = AUDIO_TTS_AZURE_SPEECH_OUTPUT_FORMAT
    
    app.state.faster_whisper_model = None
    app.state.speech_synthesiser = None
    app.state.speech_speaker_embeddings_dataset = None
    
    ########################################
    #
    # TASKS
    #
    ########################################
    
    
    app.state.config.TASK_MODEL = TASK_MODEL
    app.state.config.TASK_MODEL_EXTERNAL = TASK_MODEL_EXTERNAL
    
    app.state.config.ENABLE_SEARCH_QUERY_GENERATION = ENABLE_SEARCH_QUERY_GENERATION
    app.state.config.ENABLE_RETRIEVAL_QUERY_GENERATION = ENABLE_RETRIEVAL_QUERY_GENERATION
    app.state.config.ENABLE_AUTOCOMPLETE_GENERATION = ENABLE_AUTOCOMPLETE_GENERATION
    app.state.config.ENABLE_TAGS_GENERATION = ENABLE_TAGS_GENERATION
    app.state.config.ENABLE_TITLE_GENERATION = ENABLE_TITLE_GENERATION
    
    app.state.config.TITLE_GENERATION_PROMPT_TEMPLATE = TITLE_GENERATION_PROMPT_TEMPLATE
    app.state.config.TAGS_GENERATION_PROMPT_TEMPLATE = TAGS_GENERATION_PROMPT_TEMPLATE
    app.state.config.IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE = (
        IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE
    )
    
    app.state.config.TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE = (
        TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE
    )
    app.state.config.QUERY_GENERATION_PROMPT_TEMPLATE = QUERY_GENERATION_PROMPT_TEMPLATE
    app.state.config.AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE = (
        AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE
    )
    app.state.config.AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH = (
        AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH
    )
    
    ########################################
    #
    # WEBUI
    #
    ########################################
    
    app.state.MODELS = {}
    